#!/bin/bash

set -eu

cd $(dirname $0)/../..

auto/stackup applied-scala-certificate up \
  --region ap-southeast-2 \
  --template deploy/shared-resources/certificate.json \
  --parameters deploy/shared-resources/certificate-reaio.json \
  --tags deploy/shared-resources/tags.json

